=head1 NAME

Support Quota Add-on - Control customer work unit quotas

=head1 DESCRIPTION

This OTRS Add-on module provides an easy to use interface to control customer contracted work unit quotas.

By entering a quota to each Customer Company in your OTRS system and taking care to set the proper 'CustomerCompanyID' on your tickets (easy if you use PostMaster Filters), this add-on is able to get the total work unit quota available to a particular customer, how many work units were used in the current period and how many work units are available to that customer in the same period. Periods can be the current month or year. If the available quota is negative, there will be extra bucks in the end of the period.

The above information then appears in a widget under both AgentTicketZoom and overall Customer interfaces. That way agents can easily decide how to charge (or not) for beyond quota customers, while customers can keep track of their support quota usage.

For a complete description, installation, configuration and some useful usage notes, please read the L<README.md|https://github.com/denydias/otrs/tree/master/SupportQuota#otrs-support-quota-add-on> at the source repository.

=head1 AUTHOR AND LICENSE

Copyright (C) 2014-2017 Deny Dias, L<https://mexapi.macpress.com.br/about>

This module is licensed under the AGPL 3.

=cut
